# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  powerManagement.cpuFreqGovernor = "powersave";

  ## Prerequisite
  environment.systemPackages = with pkgs;[
    mergerfs
    snapraid 
  ];

  ### Disks

  ## System disks (Apacer AS340 PANTHER 120GB) - [DOM: N/A Approx. 2024]
  # Boot (/)	- d71c7fb0-c330-406b-b382-db41431f746b

  ## Data Pool 
  # Disk01	- de4e0096-cf57-4d81-8272-f02a3cecdbeb (WD 1TB) [DOM: TBU] - Movies
  # Disk02	- 658c34a2-1f31-4e21-a2f5-4216b68e308b (WD 1TB) [DOM: TBU] - TV Shows
  # Disk03	- 403fdf35-6d4d-44eb-b353-398fc51d92d7 (WD 1TB) [DOM: TBU] - Personal
  # Disk04	- b0c34f6f-50ea-4ee1-9dfe-8f4cbad1550e (Toshiba 1TB) [DOM: TBU] - Parity01
  # Disk05	- [DOM: TBU] - Parity02

  ###################
  ## System
  ###################
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d71c7fb0-c330-406b-b382-db41431f746b";
      fsType = "ext4";
    };

  swapDevices = [ ];

  ###################
  ## Parity
  ###################

  fileSystems."/mnt/disks/parity01" =
    { device = "/dev/disk/by-uuid/b0c34f6f-50ea-4ee1-9dfe-8f4cbad1550e";
      fsType = "btrfs";
    };

#  fileSystems."/mnt/disks/parity02" =
#    { device = "/dev/disk/by-uuid/5a8f48b7-da38-44a0-a090-f25956ffc644";
#      fsType = "btrfs";
#    };

  ###################
  ## Data Pool
  ###################

  # Media storage disks, pooled by MergerFS
  fileSystems."/mnt/disks/data01" =
    { device = "/dev/disk/by-uuid/de4e0096-cf57-4d81-8272-f02a3cecdbeb";
      fsType = "btrfs";
    };

  fileSystems."/mnt/disks/data02" =
    { device = "/dev/disk/by-uuid/658c34a2-1f31-4e21-a2f5-4216b68e308b";
      fsType = "btrfs";
    };

  fileSystems."/mnt/disks/data03" =
    { device = "/dev/disk/by-uuid/403fdf35-6d4d-44eb-b353-398fc51d92d7";
      fsType = "btrfs";
    };

  ###################
  ## MergerFS
  ###################

  fileSystems."/mnt/storage" =
    { depends = [
      # The `disk*` mounts have to be mounted in this given order.
      "/mnt/disks/data01" # Movies
      "/mnt/disks/data02" # TV Shows
      "/mnt/disks/data03" # Personal
      ];
      device = "/mnt/disks/data*";
      fsType = "mergerfs";
      options = ["defaults" "minfreespace=5G" "fsname=mergerfs-jbod"];
    };

  ###################
  ## SnapRaid
  ###################

  environment.etc."snapraid.conf".text = ''
# =============================
# SnapRAID configuration
# =============================

# Parity disks
parity /mnt/disks/parity01/snapraid.parity
#parity2 /mnt/disks/parity02/snapraid.parity

# Content files (index and checksums)
content /mnt/disks/data01/snapraid.content
content /mnt/disks/data02/snapraid.content
content /mnt/disks/data03/snapraid.content
content /mnt/disks/parity01/snapraid.content
#content /mnt/disks/parity02/snapraid.content

# Data disks
data disk01 /mnt/disks/data01
data disk02 /mnt/disks/data02
data disk03 /mnt/disks/data03

# Exclusions
exclude *.bak
exclude /tmp/
exclude /lost+found/
exclude .Trash-*/
exclude .recycle/
exclude *.partial~
exclude .AppleDouble
exclude .DS_Store
exclude thumbs.db
  '';

  ############################
  ## SnapRAID systemd services
  ############################
  systemd.services.snapraid-sync = {
    description = "SnapRAID Sync Job";
    after = [ "local-fs.target" ];
    wants = [ "local-fs.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.snapraid}/bin/snapraid sync";
    };
  };

  systemd.services.snapraid-scrub = {
    description = "SnapRAID Scrub Job";
    after = [ "local-fs.target" ];
    wants = [ "local-fs.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.snapraid}/bin/snapraid scrub -p 10 -o 10";
    };
  };

  ############################
  ## SnapRAID Timers
  ############################
  systemd.timers.snapraid-sync = {
    description = "Daily SnapRAID Sync";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "1h";
      OnUnitActiveSec = "24h";  # repeat every 24h
      Persistent = true;
    };
  };

  systemd.timers.snapraid-scrub = {
    description = "Weekly SnapRAID Scrub";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "2h";
      OnUnitActiveSec = "7d";  # repeat weekly
      Persistent = true;
    };
  };

  ############################
  ## Convenience shell aliases
  ############################
  environment.shellAliases = {
    snapdiff = "sudo snapraid diff";
    snapsync = "sudo snapraid sync";
    snapscrub = "sudo snapraid scrub -p 10 -o 10";
    snapstatus = "sudo snapraid status";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
